# Generated by Django 5.0.6 on 2025-04-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='count',
            name='time',
            field=models.CharField(default='00:00:00', max_length=100),
        ),
    ]
